apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: pipeline
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWxmbG93 #mlflow
  AWS_SECRET_ACCESS_KEY: dFQ4RnFUVlQzRVA4Rm1ndg== #tT8FqTVT3EP8Fmgv