---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: el-pipeline
spec:
  to:
    kind: Service
    name: el-pipeline-gitlab-listener-interceptor
    weight: 100
  port:
    targetPort: http-listener
  tls:
    termination: edge
  wildcardPolicy: None
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
type: Opaque
data:
  token: N0w3TmY0elNkTQ== #7L7Nf4zSdM
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: pipeline-gitlab-listener-interceptor
spec:
  serviceAccountName: pipeline
  triggers:
    - name: pipeline-trig
      interceptors:
        - gitlab:
            secretRef:
              secretName: gitlab-secret
              secretKey: token
            eventTypes:
              - Push Hook
      
      bindings:
        - ref: pipeline-trig-binding
      template:
        ref: pipeline-trig-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-trig-binding
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.url)
  - name: contenttype
    value: $(header.Content-Type)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-trig-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: trig-pipeline-run-
    spec:
      pipelineRef:
        name: pipeline
      params:
      - name: message
        value: $(tt.params.message)
      - name: contenttype
        value: $(tt.params.contenttype)
      workspaces:
        - name: workspace
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 100M
              storageClassName: gp2
              volumeMode: Filesystem
      resources:
      - name: source
        resourceSpec:
          type: git
          params:
          - name: revision
            value: $(tt.params.gitrevision)
          - name: url
            value: $(tt.params.gitrepositoryurl)